# Generated by Django 4.0.5 on 2022-06-08 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_follow_follow_unique_follow_follow_check_follow'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follow',
            new_name='Subscribe',
        ),
    ]
